### ISSUE TITLE
Reblogs with images don't show the image

### ISSUE THREAD

**Issue by Magess** [johnHackworth/goblin#14]
Not sure if this is intentional.

This is the first post.

<img width="935" alt="Screenshot 2023-12-06 at 4 02 38 PM" src="https://github.com/johnHackworth/goblin/assets/8743308/70d711a2-2286-4591-a466-8680fd61a63a">

Most of the post is an image. 

Then the user replied to their own post, creating a reblog chain, but this new post does not show the image in the original.

<img width="936" alt="Screenshot 2023-12-06 at 4 02 27 PM" src="https://github.com/johnHackworth/goblin/assets/8743308/137c01d7-5a3e-4175-bc69-c3726f2e0f0e">

**Comment by johnHackworth** [comment]
not intentional! was fixed! :D
