### ISSUE TITLE
CW in reblog chain is not hiding text in the original post

### ISSUE THREAD

**Issue by Magess** [johnHackworth/goblin#15]
Browser: Orion
OS: MacOS

I also confirmed this behavior on Firefox 120 on Windows.

Here is a reblog chain where the first post has a CW headline and hidden text, and then the reply also has a CW headline and hidden text. The text in the first post is being shown rather than hidden by the Show More. 

<img width="939" alt="Screenshot 2023-12-06 at 4 06 25 PM" src="https://github.com/johnHackworth/goblin/assets/8743308/a50b16c1-4408-4cfa-b9b7-b2b4579162c1">

The same post on Mastodon.

<img width="674" alt="Screenshot 2023-12-06 at 4 08 05 PM" src="https://github.com/johnHackworth/goblin/assets/8743308/9c267773-5fc5-4c9d-ae49-72f750e81d40">

**Comment by johnHackworth** [comment]
ok I wasn't aware of this, but checking now it doesn't seem to happen anymore
