### ISSUE TITLE
Editing in the tags box doesn't count as editing

### ISSUE THREAD

**Issue by Magess** [johnHackworth/goblin#22]
I've been trying to figure out how you have to enter tags in the tag box to make them appear.

1. Post something
2. Go to Edit the post
3. Change text in the tags box at the bottom
4. The Edit button does not highlight to save the changes.

![Screenshot 2023-12-10 at 08-05-39 goblin band](https://github.com/johnHackworth/goblin/assets/8743308/f40437ec-25e8-4d0c-a128-f42d1e21e898)

**Comment by johnHackworth** [comment]
it's fixed now!
