### ISSUE TITLE
Boosted goblin post doesn't show the reblog addition

### ISSUE THREAD

**Issue by Magess** [johnHackworth/goblin#23]
I saw @johnHackworth's reblog of a post and Boosted that version.

![Screenshot 2023-12-10 at 18-37-56 goblin band](https://github.com/johnHackworth/goblin/assets/8743308/8349ed3c-c6a4-4f39-86d6-8c0e0c90a952)

However, when the boosted post appeared at the top of my timeline, Javi's addition to the post was not attached.

![Screenshot 2023-12-10 at 18-38-15 goblin band](https://github.com/johnHackworth/goblin/assets/8743308/b1b614d8-3847-47dc-bd55-48ee52b9efd1)

Since the boost was on Javi's post, would expect the version that shows up in my timeline to also contain his post.

**Comment by johnHackworth** [comment]
hmm, yeah, that's because my own was a reply and not a boost, I think , and goblin has been struggling with how to deal with both in a different way. This particular case should work as expected right now, thought there are still some small issues around this topic
