### ISSUE TITLE
Multiple previews on the bottom of a post

### ISSUE THREAD

**Issue by Magess** [johnHackworth/goblin#25]
I do not know what is causing this. I think it has something to do with previews of tags? Only the website link should be causing a preview. 

![Screenshot 2023-12-14 at 08-13-15 goblin band](https://github.com/johnHackworth/goblin/assets/8743308/b3d4ebe3-6e95-499f-b68d-7971df14a6f5)

**Comment by johnHackworth** [comment]
it was the tags, they were being previewed too ! but it's fixed already
