### ISSUE TITLE
Copy link to original post menu item

### ISSUE THREAD

**Issue by Magess** [johnHackworth/goblin#29]
Can you put a Copy Link to Original Post item in the dots menu?

![Screenshot 2023-12-24 at 08-59-37 goblin band](https://github.com/johnHackworth/goblin/assets/8743308/5227d0b0-01f8-4bf3-bfb9-d21f2d54894c)

This is a thing I often want to do so I can share a post elsewhere.

**Comment by johnHackworth** [comment]
done!
